name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Issue to JSON
        id: issue-to-json
        uses: ./
        with:
          issue-body: |
            <!-- Required parameters are marked with an asterisk (*) -->
            
            ### Foo *
            
            Hello, World!
            
            ### Bar
            
            Hello, Universe!
          issue-template: example.md
          
      - name: Check Result
        env:
          VALUES: ${{ steps.issue-to-json.outputs.values }}
        run: |
          expected_values=$'{"foo":"Hello, World!","bar":"Hello, Universe!"}'
          if [ "$VALUES" != "$expected_values" ]; then
            echo "Unexpected result values: $VALUES"
            exit 1
          fi
